repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.7"
    hooks:
      - id: ruff
        language_version: python3.11
      - id: ruff-format
        args: [--check]
        language_version: python3.11
