site_name: chain-harvester
repo_url: https://github.com/blockanalitica/chain-harvester
site_url: https://blockanalitica.github.io/chain-harvester
site_description: A Python library designed to interface with various blockchain networks, enabling the retrieval of data.
site_author: 0xCommanderKeen
edit_uri: edit/main/docs/
repo_name: blockanalitica/chain-harvester
copyright: Maintained by <a href="https://blockanalitica.com">Block Analitica</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blockanalitica/chain-harvester
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chain-harvester

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true