[tox]
skipsdist = true
envlist = py313, py314

[testenv]
allowlist_externals = uv
commands_pre =
    uv sync --locked --group dev --active
commands =
    python -m pytest --doctest-modules tests {posargs}
