name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          version-file: VERSION
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release/${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
        if: ${{ steps.release.outputs.release_created }}

      # Logic below handles pypi release
      - name: Check out
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        if: ${{ steps.release.outputs.release_created }}
      - name: Build and publish
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build-and-publish
        env: 
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          RELEASE_VERSION: ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
